### ISSUE TITLE
[BUG] Eventlist Detail page does not show rejected applicants

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#101]
**Describe the bug**
Eventlist Detail page does not show deleted applicants.

**What Did You Want**
In the Eventlist Detail page, I wanted to list all the applicants to the service. Approved and Pending appliations are listed as expected, but deleted applicants were not shown in the applicants table.

**To Reproduce**
1. Create an event with a user (creater).
2. Apply to this event with another user (applicant).
3. Delete this new application with the same user.
4. Login as admin and go to Admindashboard-Services.
5. Find the service with deleted application and click to open detail.
6. See that the deleted application is missing.

**Expected behavior**
In the Applicants table of the Eventlist Detail page, all applicants should be seen with application status.

**Result behavior**
No error message. Missing item.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: -

**Additional context**

**Comment by emreerkaslan** [comment]
Bug is fixed and can be tested via bug/68_73_74_92_93_100
