### ISSUE TITLE
Add Superadmin role and Implement Make Remove Admin with Superadmin User

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#174]
Update user profile model to have  a superadmin role. 
Superadmin users will have all the rights to current admin role has.
Assigning admin role to any user shall be given to superadmin role. Admin users can no longer assign admin role to other users.
Remove admin role from any user shall be given to superadmin role. Admin users can no longer remove admin role from other users.

When a user is superadmin, s/he or an admin user can see the superadmin tag on the user's profile page.

**Comment by denizdikbiyik** [comment]
Only super admin can make and remove admin. Super admin can now see super admin tag too.

**Comment by muhammedgenc** [comment]
Test OK.
