### ISSUE TITLE
[BUG] Unfollow at Profile page leads to Followings Page

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#186]
**Describe the bug**
In the profile picture of another user that the current user follows, when I click Unfollow button, Followings Page is loaded.

**What Did You Want**
As a user, I wanted to unfollow a user I followed.

**To Reproduce**
1. Go to the Profile page of the user that the current user is following
2. Click on Unfollow button.
3. See the Following Page loaded, instead of remaining in the profile page.

**Expected behavior**
Unfollow button should be removed and a Follow button should become visible in the Profile page.
Current user stops following the other user.

**Result behavior**
Current user stops following the other user.
Followings Page is loaded.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: -

**Additional context**

**Comment by denizdikbiyik** [comment]
This is done with the aim to show following results at the end of this function.
