### ISSUE TITLE
Create Sequence Diagram

### ISSUE THREAD

**Issue by denizdikbiyik** [denizdikbiyik/SWE574Project#19]
Create a sequence diagram for the system.

**Comment by emreerkaslan** [comment]
Sequence diagram for featured services, communication, like service and recommendations is created.
![Sequence Diagrams](https://user-images.githubusercontent.com/67108859/160394679-603c859f-ead3-4a3d-ab01-54d91f12698a.png)

**Comment by alper-turgal** [comment]
Sequence diagram for Admin Dashboard is created
![Admin_Sequence](https://user-images.githubusercontent.com/92436207/160398308-c3b2be7d-b5bc-4974-94a0-a9046d6359a2.png)
.
