### ISSUE TITLE
[BUG] Wikidata search error when entered more than one word as keyword

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#200]
**Describe the bug**
When I entered more than one word as wikidata search keyword and click the submit button, the page throws a Keyerror exception.

**What Did You Want**
I wanted to add a two word wikidata label to a service I created. The keywords I tried are: "İçli Köfte", "Software Engineering", "Machine Learning"

**To Reproduce**
1. Go to Create Service page.
2. Click on 'I want to add a Wikidata description.' link
3. Enter the two words keyword as "Search in Wikidata:" textbox.
4. Click submit button.
5. See error

**Expected behavior**
Keyword explanations are showed.

**Result behavior**
Page throws KeyError at /wiki/ exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/92574532/165129817-c4bb430c-4053-4292-80c4-02ea79a35353.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: -

**Additional context**

**Comment by alper-turgal** [comment]
The bug has been fixed and a pull request has been sent for this issue.

**Comment by muhammedgenc** [comment]
The bug is fixed
