### ISSUE TITLE
[BUG] Other Profile Interest Add Remove Buttons

### ISSUE THREAD

**Issue by denizdikbiyik** [denizdikbiyik/SWE574Project#315]
**Describe the bug**
When a user looks at other user's profile, can see interest adding and removing buttons. They should not be seen. Only the interests should be seen, but + and - buttons should be hidden.

**What Did You Want**
Just wanted to look at a profile.

**To Reproduce**
1. Go to the website.
2. Click on any user profile.
3. See error

**Expected behavior**
A user profile page.

**Result behavior**
A user profile page with interest + and - buttons.

**Comment by emreerkaslan** [comment]
Bug is resolved and merged.
