### ISSUE TITLE
Location and Search - Sort Related Improvements

### ISSUE THREAD

**Issue by denizdikbiyik** [denizdikbiyik/SWE574Project#332]
Location will be separated for both normal services & events and admin dashboard services & events.
There will be sort by nearest.
Range to search for nearby 5 default, but maybe selected 10 too. (min 1, default 3 etc) 
Location for the text given and selected from map, but profile location should also be implemented.

**Comment by alper-turgal** [comment]
Search by location from the map and home address within a selected range feature has been added to Services and Events page. Users can also search an event or service by entering a keyword in the search bar that matches the address information of the service or event.
