### ISSUE TITLE
[BUG] - Services page loads in 9 minutes...

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#381]
**Describe the bug**
I created 1000 services. When I tried to open the services page, it took over 8 minutes to load the page. (SS below: from 02.07 to 02.16)

**Screenshots**

![services_load_9_mins](https://user-images.githubusercontent.com/92574532/169782061-e2a30ad2-25de-46b9-a4d5-10d4ee13798c.png)

**Comment by emreerkaslan** [comment]
Bug is fixed and merged into main. It takes 10 seconds max. for page to load now.
