### ISSUE TITLE
Create Glossary

### ISSUE THREAD

**Issue by denizdikbiyik** [denizdikbiyik/SWE574Project#4]
Create a glossary for the fundamental concepts of the system in order to clarify the requirements.

**Comment by alper-turgal** [comment]
Create a glossary for the user..

**Comment by denizdikbiyik** [comment]
[Glossary](https://github.com/denizdikbiyik/SWE574Project/wiki/04-Glossary)

**Comment by alper-turgal** [comment]
Explanations have been written for the fundamental terms and concepts of the system. Some revisions may be needed.The list will be further extended.

**Comment by denizdikbiyik** [comment]
The wiki link is [Glossary](https://github.com/denizdikbiyik/SWE574Project/wiki/04-Glossary).
