### ISSUE TITLE
[BUG] Non-admin users can solve their own complaints instead of editing/deleting

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#426]
**Describe the bug**
As a user I wanted to edit/delete the complaint I created. When I clicked it the solution page is opened.

**To Reproduce**
1. Go to All users page and create a complaint about that user.
2. Click on the username on top right of the screen and select My Complaints from the dropdown menu
3. Click on the complaint you want to edit/delete
4. Select past complaints by me on the profile page.
5. Click on the complaint to edit/delete.
6. See complaint solution page is opened instead.

**Comment by denizdikbiyik** [comment]
Page changes are done, but all complaint related pages and links, functions should be tested like admin dashboard complaints page, my complaints page under dropdown, complaint button when opening a profile, past complaints link under complaint button, 2 links when admin opens a profile those are complaints created about and complaints created by.

**Comment by muhammedgenc** [comment]
test ok
