### ISSUE TITLE
Update Sequence Diagram

### ISSUE THREAD

**Issue by denizdikbiyik** [denizdikbiyik/SWE574Project#43]
Make the diagram parts separated for sequence diagram on the [Software Design Wiki](https://github.com/denizdikbiyik/SWE574Project/wiki/08-Software-Design) page.

**Comment by denizdikbiyik** [comment]
Divide the parts and edit service event combined diagrams to be separated too.

**Comment by emreerkaslan** [comment]
Sequence diagrams for featured services, communication, like service and recommendations is re-created.

**Comment by emreerkaslan** [comment]
Communication and like is updated.
![RemoveLike](https://user-images.githubusercontent.com/67108859/162288143-a2793e09-d702-41d6-96df-3af7c053ef3d.png)
![AddLike](https://user-images.githubusercontent.com/67108859/162288156-55d3b030-d3c9-4878-a80e-c696eeefbc27.png)
![AddMessage](https://user-images.githubusercontent.com/67108859/162288158-ac136277-d4e8-440f-926a-c6a10798a272.png)
![EditMessage](https://user-images.githubusercontent.com/67108859/162288163-393ecbde-b472-4ff9-a920-00adfe60efdf.png)
![DeleteMessage](https://user-images.githubusercontent.com/67108859/162288169-a63d9ae6-d2d7-493f-b7ad-a7f56ccf6f09.png)

**Comment by alper-turgal** [comment]
![AdminListService](https://user-images.githubusercontent.com/92436207/162529436-ca98bd5f-47a0-4d81-8b7e-42b1681ee524.png)
![AdminListEvent](https://user-images.githubusercontent.com/92436207/162529539-9a852f24-30e2-4756-b2c2-a1363ee3b511.png)
![AdminListUser](https://user-images.githubusercontent.com/92436207/162529716-318d6400-2129-45f4-b7aa-8a67c77bf26c.png)
![AdminDeactivateService](https://user-images.githubusercontent.com/92436207/162529830-fe4113bf-0c88-477c-b9a6-b5e4358fea30.png)
![AdminDeactivateUser](https://user-images.githubusercontent.com/92436207/162529969-4b917419-a3c1-4769-8f5b-ba1a0fe088fe.png)

**Comment by emreerkaslan** [comment]
Latest sequence diagram updates are ready.
![Add Featured](https://user-images.githubusercontent.com/67108859/162609367-e2914bf8-7587-4bc1-99c4-e6ea9ef005e4.png)
![Add Like](https://user-images.githubusercontent.com/67108859/162609369-a1f68cb4-7fb4-47a2-9bd5-c18a00efbe8b.png)
![Add Message](https://user-images.githubusercontent.com/67108859/162609370-f02fc462-dc48-48b4-9ec3-233cefc9b981.png)
![Confirm Recommendation](https://user-images.githubusercontent.com/67108859/162609371-33e29a93-acfa-46d3-94d0-6c122a221f09.png)
![Create Recommendation](https://user-images.githubusercontent.com/67108859/162609372-b45c27eb-63c0-4796-9681-0365b48cc4ba.png)
![Delete Featured](https://user-images.githubusercontent.com/67108859/162609375-3b7dfb44-bed6-420f-80a9-51ce2cdfefd1.png)
![Delete Message](https://user-images.githubusercontent.com/67108859/162609376-8b120294-1041-401a-b7fb-756aa4b5b153.png)
![Delete Recommendation](https://user-images.githubusercontent.com/67108859/162609377-3fb1b592-f9f5-4638-9fa5-0792c1eb8730.png)
![Edit Message](https://user-images.githubusercontent.com/67108859/162609378-a8a8a8d2-6724-490f-91b8-5664ee95b5f9.png)
![Remove Like](https://user-images.githubusercontent.com/67108859/162609379-8c035535-1280-4173-a586-d9c1c2293434.png)

**Comment by alper-turgal** [comment]
![SearchService](https://user-images.githubusercontent.com/92436207/171521532-c260b853-c40a-41b1-a23e-39d78ce27156.png)
