### ISSUE TITLE
Create Scenarios for The Customer Presentation 1

### ISSUE THREAD

**Issue by denizdikbiyik** [denizdikbiyik/SWE574Project#44]
The customer presentation will be on 04.04.22 at 19.00. Prepare scenarios to present the system. Add them to the [wiki page.](https://github.com/denizdikbiyik/SWE574Project/wiki/11-Customer-Presentation-1-Scenarios)

**Comment by muhammedgenc** [comment]
The scenarios created and implemented before the customer presentation and added to the wiki page https://github.com/denizdikbiyik/SWE574Project/wiki/11-Customer-Presentation-1-Scenarios
