### ISSUE TITLE
[BUG] Admin solves the deleted complaint, user deletes/edits solved complaint, messes up notification count

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#445]
**Describe the bug**
User issues a complaint. This sends a notification to admin.
User edits the complaint. This sends another notification to admin.
User opens the complaint detail (edit/delete) page
Admin opens the complaint solution page
Case1: Admin solves the complaint after user deletes
Case2: Admin solves the complaint previous version after user edits
Case3: User edits the solved complaint
Case4: User deletes the solved complaint
Case1 and Case4 lead to negative notification count.

**Comment by denizdikbiyik** [comment]
Bugs are fixed.

**Comment by muhammedgenc** [comment]
test ok
