### ISSUE TITLE
[BUG] Approved Recommendation Not Shown As Approved on Main Page

### ISSUE THREAD

**Issue by denizdikbiyik** [denizdikbiyik/SWE574Project#453]
**Describe the bug**
When a recommendation is approved which was seen on the main page, it redirects to the recommendations page and the approvement is seen there. When main page is opened again, it shows the recommendation to approve or decline again. The approvement should be shown there too as approved. This should be checked for decline also.

**What Did You Want**
Wanted to approve a recommendation.

**To Reproduce**
1. Go to main page
2. Approve recommendation
3. Go again main page

**Expected behavior**
Approvement should be shown.

**Result behavior**
Approve and decline buttons are seen again

**Comment by emreerkaslan** [comment]
Bug is fixed and merged into main.
