### ISSUE TITLE
[BUG] Servicelist Detail page does not show rejected applicants.

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#68]
**Describe the bug**
Servicelist Detail page does not show rejected applicants.

**What Did You Want**
In the Servicelist Detail page, I wanted to list all the applicants to the service. Approved and Pending appliacations are listed as expected, but rejected applicants were not shown in the applicants table.

**To Reproduce**
1. Create a service with a user (creater).
2. Apply to this service with another user (applicant).
3. Login with creater and reject the application of the applicant.
4. Login as admin and go to Admindashboard-Services.
5. Find the service with rejected application and click to open detail.
6. See that the rejected application is missing.

**Expected behavior**
In the Applicants table of the Servicelist Detail page, all applicants should be seen with application status.

**Result behavior**
No error message. Missing item.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: -

**Additional context**

**Comment by denizdikbiyik** [comment]
isDeleted implementation is done for the models and views are changed accordingly.

**Comment by emreerkaslan** [comment]
Bug is fixed and can be tested via bug/68_73_74_92_93_100
