### ISSUE TITLE
[BUG] Service Detail Page Admin users cannot delete other users communication

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#71]
**Describe the bug**
Admin users cannot delete the messages of another user in the communication section of the Service Detail page.

**What Did You Want**
As an admin user, I wanted to delete an inappropriate message sent by another user under a service. But there was no delete button active for the admin user.

**To Reproduce**
1. As admin go to Service Detail page of a service which already has message/s submitted.
2. Scroll down to the communication section under the service detail and applicants.
3. Admin cannot see a delete button by the end of the messages, where normally the message sender sees a delete button.

**Expected behavior**
A delete button should be visible for admin at the end of each message and it should delete the message submitted by another user.

**Result behavior**
No error message. Missing button.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: -

**Additional context**

**Comment by denizdikbiyik** [comment]
Admins now can delete messages.
