### ISSUE TITLE
[BUG] Service Detail Page Admin users cannot see pending applicants

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#73]
**Describe the bug**
Admin users cannot see pending applicants in the application section of the Service Detail page.

**What Did You Want**
As an admin user, I wanted to all the applicants of a service. Only approved applicants were visible, pending applicants were not visible to the admin user.

**To Reproduce**
1. As admin go to Service Detail page of a service which already has at least one approved and one pending applicants.
2. Scroll down to the applications section under the service detail.
3. Admin cannot see the pending applicants.

**Expected behavior**
All applicants of a service should be visible to admin.

**Result behavior**
No error message. Missing list-item.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: -

**Additional context**

**Comment by emreerkaslan** [comment]
Bug is fixed and can be tested via bug/68_73_74_92_93_100
