### ISSUE TITLE
[BUG] No following users page

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#75]
**Describe the bug**
A user can follow other users, but there is no page or list to view which users are being followed by a user.

**What Did You Want**
As as user, I wanted to check which users I am following.

**To Reproduce**

**Expected behavior**
A page or list where the users are followed by a user are shown/listed.

**Result behavior**
There is no such feature in the project.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: -

**Additional context**
In the list of the user, each user should have a link to their profile page, where the viewer can use the unfollow button to stop following them.

**Comment by denizdikbiyik** [comment]
Followings page is implemented.
