### ISSUE TITLE
Create Version Control Protocol

### ISSUE THREAD

**Issue by denizdikbiyik** [denizdikbiyik/SWE574Project#8]
Write version control protocol and create a wiki page for it.

**Comment by denizdikbiyik** [comment]
[Version Control Protocol](https://github.com/denizdikbiyik/SWE574Project/wiki/06-Version-Control-Protocol)

**Comment by alper-turgal** [comment]
Created, the wiki link:
[Version Control Protocol](https://github.com/denizdikbiyik/SWE574Project/wiki/06-Version-Control-Protocol)
