### ISSUE TITLE
[BUG] Servicelist Detail Applicant's Profile link

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#92]
**Describe the bug**
In the Servicelist Detail page, the applicants listed in the Applications table should be linked to their profile.

**What Did You Want**
In the Servicelist Detail page, I wanted to see the profile of the applicants to the service. 

**To Reproduce**
1. Create a service with a user (creater).
2. Apply to this service with another user (applicant).
3. Login as admin and go to Admindashboard-Services.
4. Find the service with application and click to open detail.
5. See there is no hyperlink on the applicant's username.

**Expected behavior**
Applicant usernames should be linked to their own profile.

**Result behavior**
No hyperlink

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: -

**Additional context**

**Comment by emreerkaslan** [comment]
Bug is fixed and can be tested via bug/68_73_74_92_93_100
