### ISSUE TITLE
Service Detail Communication Layout Change

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#94]
In the Service Detail Page, communications look not visually pleasing. Messages and delete buttons are intertwined. It is better if a message has a standard form.
*Messages shall start at a new line with an indent
*The size of the delete button shall be smaller.
*The delete button shall be in a new line with the same indent of the message.

Current look:
![image](https://user-images.githubusercontent.com/92574532/163715545-88b43a9d-d690-491c-9d4a-4e4b788722a8.png)
New look:
![image](https://user-images.githubusercontent.com/92574532/163715738-4a3109ed-6650-4762-8133-91f8257fca83.png)

**Comment by denizdikbiyik** [comment]
Communication layout is improved.
