### ISSUE TITLE
[BUG] Userlist Select Dates Submit shows all users

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#95]
**Describe the bug**
In the Userlist page, when Select Dates was chosen as Period and clicked the submit button all users are listed. When Beginning Date and Ending Date fields become visible, no users shall be listed.

**What Did You Want**
As an admin user, I wanted to see if the Userlist period filter's Select Dates choice was working properly. 

**To Reproduce**
1. Login as admin and go to Admindashboard-Users.
2. Chose "Select Dates" in the "Choose a Period" combobox.
3. Click "Submit" to see the Beginning Date and Ending Date fields.
4. See all users are listed.

**Expected behavior**
No users listed.
Beginning Date and Ending Date fields to be visible.

**Result behavior**
All users are listed.
Beginning Date and Ending Date fields are visible.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: -

**Additional context**

**Comment by onemli1** [comment]
Bugs are solved.

**Comment by muhammedgenc** [comment]
Bug fixed.
