### ISSUE TITLE
[BUG] Userlist No Dates selection error message

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#96]
**Describe the bug**
In the Userlist page, in the case Select Dates was chosen as Period, when clicked the submit button without choosing a Beginning Date and an Ending Date, an error message should be shown: "Please select a Beginning Date and an Ending Date."

**What Did You Want**
As an admin user, I wanted to see if the Userlist period filter's Select Dates choice was working properly. In this scenario, I did not select any dates and wanted to see an error message and no users listed.

**To Reproduce**
1. Login as admin and go to Admindashboard-Users.
2. Chose "Select Dates" in the "Choose a Period" combobox.
3. Click "Submit" to see the Beginning Date and Ending Date fields.
4. Click "Submit" once again, without selecting any date in both Beginning Date and Ending Date fields.
5. See all users listed.

**Expected behavior**
No users listed.
Under the "Submit" button, following error message should be shown: "Please select a Beginning Date and an Ending Date."

**Result behavior**
All users are listed.
No error message.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: -

**Additional context**

**Comment by onemli1** [comment]
Bugs are solved.

**Comment by muhammedgenc** [comment]
Bug fixed.
