### ISSUE TITLE
[BUG] Userlist selection of Beginning Date older than Ending Date

### ISSUE THREAD

**Issue by muhammedgenc** [denizdikbiyik/SWE574Project#99]
**Describe the bug**
In the Userlist page, in the case Select Dates was chosen as Period, when clicked the submit button after choosing a Beginning Date and an Ending Date but choosing a Beginning Date older than the chosen Ending Date, no users should be listed and an error message should be shown: "Beginning Date cannot be older than the Ending Date."

**What Did You Want**
As an admin user, I wanted to see if the Userlist period filter's Select Dates choice was working properly. In this scenario, I selected a Beginning Date older than an Ending Date and wanted to see an error message and no users listed.

**To Reproduce**
1. Login as admin and go to Admindashboard-Users.
2. Chose "Select Dates" in the "Choose a Period" combobox.
3. Click "Submit" to see the Beginning Date and Ending Date fields.
4. Select a date in the Ending Date field.
5. Select a date in the Beginning Date field older than the Ending Selection
6. Click "Submit".
7. See "Number of Users found: 0" message

**Expected behavior**
No users listed.
Under the "Submit" button, following error message should be shown: "Beginning Date cannot be older than the Ending Date."

**Result behavior**
0 users listed.
No error message.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: -

**Additional context**

**Comment by onemli1** [comment]
Bugs are solved.

**Comment by muhammedgenc** [comment]
Bug fixed.
